name: "Project Bedrock CI/CD"

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # This creates the physical file the S3 Backend looks for first
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -backend-config="region=us-east-1" \
            -reconfigure \
            -input=false
- name: Terraform Init
        env:
          AWS_REGION: us-east-1
        run: terraform init -input=false

      - name: Terraform Apply
        env:
          AWS_REGION: us-east-1
        run: terraform apply -auto-approve -input=false
